title: "Olivia Baskerville"
description: "Personal website of Olivia Baskerville"
url: "https://oliviabaskerville.github.io"
baseurl: ""

remote_theme: pages-themes/merlot@v0.2.0
plugins:
- jekyll-remote-theme